// Code generated by vango. DO NOT EDIT.
// Source: vango_state_manifest.json
// Generator: vango gen bindings

package components

import "github.com/vango-go/vango/pkg/runtime"

func init() {
	runtime.SetEmbeddedBindingsHash("9828a8bd521f8eef")
	runtime.RegisterSetupCallsites(map[string][]runtime.SetupCallsite{
		"github.com/vango-go/vai-lite/app/components.AccessPage": {
			{Line: 109, SetupIndex: 0},
		},
		"github.com/vango-go/vai-lite/app/components.BillingPage": {
			{Line: 484, SetupIndex: 0},
		},
		"github.com/vango-go/vai-lite/app/components.ChatPage": {
			{Line: 35, SetupIndex: 0},
		},
		"github.com/vango-go/vai-lite/app/components.DevelopersPage": {
			{Line: 146, SetupIndex: 0},
		},
		"github.com/vango-go/vai-lite/app/components.HomePage": {
			{Line: 19, SetupIndex: 0},
		},
		"github.com/vango-go/vai-lite/app/components.KeysPage": {
			{Line: 316, SetupIndex: 0},
		},
		"github.com/vango-go/vai-lite/app/components.ObservabilityPage": {
			{Line: 745, SetupIndex: 0},
		},
		"github.com/vango-go/vai-lite/app/components.SettingsOverviewPage": {
			{Line: 58, SetupIndex: 0},
		},
	})
	runtime.RegisterBindings(map[string]runtime.BindingInfo{
		"github.com/vango-go/vai-lite/app/components.BillingPage#setup0.local.action@0": {
			StableID:         "6da70323",
			DebugName:        "topup",
			CodecFingerprint: "fp:v1:2565b845c2c6ac88ac4cf91f374fd3a6a04ce4b1fde15031e1897dd5aace41f8",
			Kind:             "action",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.BillingPage#setup0.local.effect@0": {
			StableID:         "7ab98b23",
			DebugName:        "topup",
			CodecFingerprint: "fp:v1:bb2c9bbd8e42d1c77679ba12b77cdd888a502ceddd40605a33803cabc6da2578",
			Kind:             "effect",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.BillingPage#setup0.local.resource@0": {
			StableID:         "9417ca9a",
			DebugName:        "data",
			CodecFingerprint: "fp:v1:6575c8fe286aafa7db86c6d9b70bea5dfd0c243a5d621a564a62258a476da0e4",
			Kind:             "resource",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.BillingPage#setup0.local.signal@0": {
			StableID:         "224c1166",
			DebugName:        "amountUSD",
			CodecFingerprint: "fp:v1:30a63eee6dca6c358b70d73211e051d443c38b6afee573489505c9b7d3b8dcbf",
			Kind:             "signal",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.BillingPage#setup0.local.signal@1": {
			StableID:         "507df776",
			DebugName:        "amountError",
			CodecFingerprint: "fp:v1:30a63eee6dca6c358b70d73211e051d443c38b6afee573489505c9b7d3b8dcbf",
			Kind:             "signal",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.BillingPage#setup0.local.signal@2": {
			StableID:         "e55a4873",
			DebugName:        "pendingCheckoutURL",
			CodecFingerprint: "fp:v1:30a63eee6dca6c358b70d73211e051d443c38b6afee573489505c9b7d3b8dcbf",
			Kind:             "signal",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.ChatPage#setup0.local.action@0": {
			StableID:         "a31daec5",
			DebugName:        "newConversation",
			CodecFingerprint: "fp:v1:477df8582f751b98ee7d050d85782011d752fde32159170b23d074e686b1874a",
			Kind:             "action",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.ChatPage#setup0.local.action@1": {
			StableID:         "19431aaa",
			DebugName:        "uploadIntent",
			CodecFingerprint: "fp:v1:ce36c795ecaa53729a4c760d973743e9f855ee644eedaf4bf8e3e1b8031fe34f",
			Kind:             "action",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.ChatPage#setup0.local.action@2": {
			StableID:         "a7e506c4",
			DebugName:        "uploadClaim",
			CodecFingerprint: "fp:v1:bc79e8ae2ac915df35d445706fc63d55635e3c514d9601a74a198e02246b7870",
			Kind:             "action",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.ChatPage#setup0.local.action@3": {
			StableID:         "467a74b7",
			DebugName:        "submitChat",
			CodecFingerprint: "fp:v1:54a3e5df375662583ba993fda731039ca14479801cf7fdff4776f03c991bebd7",
			Kind:             "action",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.ChatPage#setup0.local.effect@0": {
			StableID:         "575813fd",
			DebugName:        "newConversation",
			CodecFingerprint: "fp:v1:bb2c9bbd8e42d1c77679ba12b77cdd888a502ceddd40605a33803cabc6da2578",
			Kind:             "effect",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.ChatPage#setup0.local.resource@0": {
			StableID:         "fc915d8d",
			DebugName:        "pageData",
			CodecFingerprint: "fp:v1:3fcdc89206ef1f5d6c85553162d096728f2455fd3250fb2a3d8749e1c1cb21ff",
			Kind:             "resource",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.ChatPage#setup0.local.signal@0": {
			StableID:         "915b3ee0",
			DebugName:        "pendingConversationID",
			CodecFingerprint: "fp:v1:30a63eee6dca6c358b70d73211e051d443c38b6afee573489505c9b7d3b8dcbf",
			Kind:             "signal",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.DevelopersPage#setup0.local.action@0": {
			StableID:         "cdf3aaeb",
			DebugName:        "createKey",
			CodecFingerprint: "fp:v1:2daec14fd99835e3a1ea383c80359588f330b0d913ab0a13c9b947380fe17ebf",
			Kind:             "action",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.DevelopersPage#setup0.local.action@1": {
			StableID:         "43805db0",
			DebugName:        "revokeKey",
			CodecFingerprint: "fp:v1:d7d7e96309bd7c12dc347481a0351d84a6b18616037a2252686623c854502123",
			Kind:             "action",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.DevelopersPage#setup0.local.resource@0": {
			StableID:         "13403582",
			DebugName:        "keys",
			CodecFingerprint: "fp:v1:439b6889bc1b552063f3c4b521f1ed567b3bd2ab91e5e23cd6e0d9c0af927e14",
			Kind:             "resource",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.DevelopersPage#setup0.local.signal@0": {
			StableID:         "3f0a996b",
			DebugName:        "name",
			CodecFingerprint: "fp:v1:30a63eee6dca6c358b70d73211e051d443c38b6afee573489505c9b7d3b8dcbf",
			Kind:             "signal",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.DevelopersPage#setup0.local.signal@1": {
			StableID:         "5ee8243a",
			DebugName:        "nameError",
			CodecFingerprint: "fp:v1:30a63eee6dca6c358b70d73211e051d443c38b6afee573489505c9b7d3b8dcbf",
			Kind:             "signal",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.DevelopersPage#setup0.local.signal@2": {
			StableID:         "5c3de9bb",
			DebugName:        "createdKey",
			CodecFingerprint: "fp:v1:21ffeba73e1a0b295f09ee478f019089666a9f8d2417e4fc030e0d6ccefc9519",
			Kind:             "signal",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.HomePage#setup0.local.action@0": {
			StableID:         "90c5f24e",
			DebugName:        "newConversation",
			CodecFingerprint: "fp:v1:477df8582f751b98ee7d050d85782011d752fde32159170b23d074e686b1874a",
			Kind:             "action",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.HomePage#setup0.local.effect@0": {
			StableID:         "f5dbeeff",
			DebugName:        "conversations",
			CodecFingerprint: "fp:v1:bb2c9bbd8e42d1c77679ba12b77cdd888a502ceddd40605a33803cabc6da2578",
			Kind:             "effect",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.HomePage#setup0.local.effect@1": {
			StableID:         "666b11b0",
			DebugName:        "conversations",
			CodecFingerprint: "fp:v1:bb2c9bbd8e42d1c77679ba12b77cdd888a502ceddd40605a33803cabc6da2578",
			Kind:             "effect",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.HomePage#setup0.local.resource@0": {
			StableID:         "345e3505",
			DebugName:        "conversations",
			CodecFingerprint: "fp:v1:79d819bf69474082f843f088decf9582346231372055e29e617a3180aac6cf15",
			Kind:             "resource",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.HomePage#setup0.local.signal@0": {
			StableID:         "a279e41a",
			DebugName:        "redirected",
			CodecFingerprint: "fp:v1:a0e185526259a5c89de3668f26ecdd3229878df677ad6713dd7b0a2027752c16",
			Kind:             "signal",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.HomePage#setup0.local.signal@1": {
			StableID:         "3861d93d",
			DebugName:        "pendingConversationID",
			CodecFingerprint: "fp:v1:30a63eee6dca6c358b70d73211e051d443c38b6afee573489505c9b7d3b8dcbf",
			Kind:             "signal",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.KeysPage#setup0.local.action@0": {
			StableID:         "120914b6",
			DebugName:        "storeSecret",
			CodecFingerprint: "fp:v1:7ac69785e1bc1b517b1cbdfa76fd0dfa4a1c20b2d974aab865f5feb20424e457",
			Kind:             "action",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.KeysPage#setup0.local.action@1": {
			StableID:         "8af64820",
			DebugName:        "deleteSecret",
			CodecFingerprint: "fp:v1:d7d7e96309bd7c12dc347481a0351d84a6b18616037a2252686623c854502123",
			Kind:             "action",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.KeysPage#setup0.local.resource@0": {
			StableID:         "ce93fd48",
			DebugName:        "secrets",
			CodecFingerprint: "fp:v1:ae5203d202e0ec5cc7c255065bf5bbb12f3e904c30a7acce3df10ba3449fb38e",
			Kind:             "resource",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.KeysPage#setup0.local.signal@0": {
			StableID:         "2c0fb111",
			DebugName:        "provider",
			CodecFingerprint: "fp:v1:30a63eee6dca6c358b70d73211e051d443c38b6afee573489505c9b7d3b8dcbf",
			Kind:             "signal",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.KeysPage#setup0.local.signal@1": {
			StableID:         "bbed5217",
			DebugName:        "secretValue",
			CodecFingerprint: "fp:v1:30a63eee6dca6c358b70d73211e051d443c38b6afee573489505c9b7d3b8dcbf",
			Kind:             "signal",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.KeysPage#setup0.local.signal@2": {
			StableID:         "95ff0730",
			DebugName:        "formError",
			CodecFingerprint: "fp:v1:30a63eee6dca6c358b70d73211e051d443c38b6afee573489505c9b7d3b8dcbf",
			Kind:             "signal",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.ObservabilityPage#setup0.local.resource@0": {
			StableID:         "4f9b098a",
			DebugName:        "keys",
			CodecFingerprint: "fp:v1:439b6889bc1b552063f3c4b521f1ed567b3bd2ab91e5e23cd6e0d9c0af927e14",
			Kind:             "resource",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.ObservabilityPage#setup0.local.resource@1": {
			StableID:         "209b86a5",
			DebugName:        "data",
			CodecFingerprint: "fp:v1:4bb35ebb94bcbbfbaa7b61551a25fdb5f25fe6efed3d2b71525839d430fb71cb",
			Kind:             "resource",
			Class:            "local",
		},
		"github.com/vango-go/vai-lite/app/components.SettingsOverviewPage#setup0.local.resource@0": {
			StableID:         "48288473",
			DebugName:        "data",
			CodecFingerprint: "fp:v1:d24f3a7ccfcc0e9aba844e310fe0c996952919262fb88a65a38ac65d72777d2d",
			Kind:             "resource",
			Class:            "local",
		},
	})
}
