// Code generated by vango. DO NOT EDIT.

package routes

import (
	chat "github.com/vango-go/vai-lite/app/routes/chat"
	chat_id_ "github.com/vango-go/vai-lite/app/routes/chat/id_"
	settings "github.com/vango-go/vai-lite/app/routes/settings"
	"github.com/vango-go/vango"
)

// Register adds all routes to the app.
// Generated by `vango dev` or `vango gen routes`.
func Register(app *vango.App) {
	// Layouts
	app.Layout("/", Layout)
	app.Layout("/settings", settings.Layout)

	// Middleware
	app.Middleware("/chat", chat.Middleware()...)
	app.Middleware("/settings", settings.Middleware()...)

	// Pages
	app.Page("/settings/access", settings.AccessPage)
	app.Page("/settings/billing", settings.BillingPage)
	app.Page("/settings/developers", settings.DevelopersPage)
	app.Page("/settings/keys", settings.KeysPage)
	app.Page("/settings/observability", settings.ObservabilityPage)
	app.Page("/chat/:id", chat_id_.ShowPage)
	app.Page("/settings", settings.IndexPage)
	app.Page("/", IndexPage)
}

// Route path constants for type-safe linking.
const (
	RouteIndex = "/"
	RouteChatID = "/chat/:id"
	RouteSettings = "/settings"
	RouteSettingsAccess = "/settings/access"
	RouteSettingsBilling = "/settings/billing"
	RouteSettingsDevelopers = "/settings/developers"
	RouteSettingsKeys = "/settings/keys"
	RouteSettingsObservability = "/settings/observability"
)
