// Code generated by vango. DO NOT EDIT.

package routes

import (
	"github.com/vango-go/vango"
)

// Register adds all routes to the app.
// Generated by `vango dev` or `vango gen routes`.
func Register(app *vango.App) {
}

